# Generated by Django 2.2.3 on 2019-07-06 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
